spring:

  datasource:

      username: newroot

      password: root@123

      url: jdbc:mysql://${DB_HOST:localhost}:3306/account?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

  jpa:

      hibernate:

        ddl-auto: update

      show-sql: true

      properties:

        hibernate:

          dialect: org.hibernate.dialect.MySQLDialect

  jackson:

    serialization:

      fail-on-empty-beans: false

server:

  port: 0

  error:

    include-message: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/
customProperty:
    test : abhi
management:

  endpoints:

    web:

      exposure:

        include: refresh,health

api:
  customer: http://CUSTOMER-SERVICE/customer
