spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERViCE
          predicates:
            - Path= /api/account/**
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERViCE
          predicates:
            - Path= /api/customer/**
server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
